### ISSUE TITLE
Notes for multiple issues

### ISSUE THREAD

**Issue by wcooley** [wcooley/puppet-rundeck#1]
As I am initially setting up Rundeck and trying to use this module, I am running into a number of issues, which I intend eventually to address individually but in the meantime I will record them here in this one issue.
- LDAP JAAS config not quite granular enough:
  - [x] Flag for LDAPS & port -  **wcooley/feature-ldap-url** (issue #61; PR #64)
  - [x] `roleMemberAttribute` vs `roleUsernameMemberAttribute` - **wcooley/feature-ldap/rule_username_member_attribute** (issue #62; PR #65)
  - [x] ~~Caching vs Combined module~~ (caching seems to be fine for me)
  - [x] ~~`storePass` & `useFirstPass`? (check that they're needed)~~ (WFM w/o them)
  - Import certs?
- log4j format is broken - does it even need to be managed?
  - [x] fix format - **wcooley/fix-log4j-format** (issue #57; PR #58)
  - [ ] managed it by augeas instead?
  - [ ] enable debug for authorization?
- [x] `RDECK_JVM` in `profile` needs to be extensible, by making `$jvm_args` (currently only in `params.pp`) accessible. I need to be able to specify `server.http.{port,host}`, etc. - **wcooley/feature-jvm-args** (issue #59; PR #60)
- `realm.properties`:
  - [ ] Allow excluding `admin_*` altogether or add additional roles?
- [ ] Allow setting security role name in `exp/webapp/WEB-INF/web.xml`
- [ ] Where did the defines go? (under `rundeck::config::*`, not `rundeck::*`) (doc update)
- [ ] Cross-management of `/etc/facter/{,facts.d}`
- [ ] Private classes. Yuck!

**Comment by liamjbennett** [comment]
Hi,
Firstly I want to apologise that you are having a rough initial experience with this module.

Secondly I want to give you a massive thank you for the clearly large amount of effort you are putting into contributing changes. It is much appreciated.

**Comment by wcooley** [comment]
Thanks @liamjbennett; it's not been a bad initial experience -- there have just been a handful of differences in what it was able to do from what I needed it to do.

Thanks for getting to my PRs quickly too.  Sorry it's burst of so many PRs -- after using the module for setting up the yum repo and installing the package and initially configuring it, I disabled it and worked on the initial Rundeck config directly and now I'm working on integrating my changes.

**Comment by liamjbennett** [comment]
Ha. Tbh that is how I started working on it.

I am now at the stage of trying to read and understand the docs in order to fill in the gaps so I am glad for your help.
